// ES became ES   1- to work with its subject code
// ART  CS, INT  CS, MUS  CS, W&L  CS have 2 spaces in their subject code
export const SUBJECTCODES = ["ANTH", "ART", "ART  CS", "ARTHI", "ARTST", "AS AM", "ASTRO", "BIOE", "BIOL", "BIOL CS", "BL ST", "CH E", "CHEM CS", "CHEM", "CH ST", "CHIN", "CLASS", "COMM", "C LIT", "CMPSC", "CMPSCCS", "CMPTG", "CMPTGCS", "CNCSP", "DANCE", "DYNS", "EARTH", "EACS", "EEMB", "ECON", "ED", "ECE", "ENGR", "ENGL", "EDS", "ESM", "ENV S", "ESS", "ES   1-", "FEMST", "FAMST", "FR", "GEN S", "GEN SCS", "GEOG", "GER", "GPS", "GLOBL", "GRAD", "GREEK", "HEB", "HIST", "IQB", "INT", "INT  CS", "ITAL", "JAPAN", "KOR", "LATIN", "LAIS", "LING", "LIT", "LIT CS", "MARSC", "MARIN", "MARINCS", "MATRL", "MATH", "MATH CS", "ME", "MAT", "ME ST", "MES", "MS", "MCDB", "MUS", "MUS  CS", "MUS A", "PHIL", "PHYS", "PHYS CS", "POL S", "PORT", "PSY", "RG ST", "RENST", "RUSS", "SLAV", "SOC", "SPAN", "SHS", "PSTAT", "TMP", "THTR", "WRIT", "W&L CSW", "W&L", "W&L  CS"];

export const QUARTERMAP = {
    "1": "Winter",
    "2": "Spring",
    "3": "Summer",
    "4": "Fall"
};

export const MAJORS: string[] = [
    "Actuarial Science",
    "Anthropology",
    "Applied Mathematics",
    "Aquatic Biology",
    "Art for College of Creative Studies",
    "Art for College of Letters & Science",
    "Asian American Studies",
    "Asian Studies",
    "Biochemistry",
    "Biology",
    "Biological Sciences",
    "Biopsychology",
    "Black Studies",
    "Chemical Engineering",
    "Chemistry",
    "Chemistry and Biochemistry",
    "Chicano & Chicana Studies",
    "Chinese",
    "Classics",
    "Communication",
    "Comparative Literature",
    "Computer Engineering",
    "Computer Science",
    "Computing",
    "Dance",
    "Earth Science",
    "Ecology & Evolution",
    "Economics",
    "Economics & Accounting",
    "Electrical Engineering",
    "English",
    "Environmental Studies",
    "Feminist Studies",
    "Film & Media Studies",
    "Financial Mathematics & Statistics",
    "French",
    "Geography",
    "German",
    "Global Studies",
    "History",
    "History of Art & Architecture",
    "History of Public Policy & Law",
    "Hydrologic Sciences & Policy",
    "Italian Studies",
    "Japanese",
    "Language, Culture & Society",
    "Latin American & Iberian Studies",
    "Linguistics",
    "Marine Science",
    "Mathematics",
    "Mathematics for College of Letters & Science",
    "Mechanical Engineering",
    "Medieval Studies",
    "Middle East Studies",
    "Molecular & Cellular Biology",
    "Music Composition",
    "Music Studies",
    "Philosophy",
    "Physics for College of Creative Studies",
    "Physics for College of Letters & Science",
    "Physiology",
    "Political Science",
    "Portuguese",
    "Psychological & Brain Sciences",
    "Religious Studies",
    "Russian & East European Studies",
    "Sociology",
    "Spanish",
    "Statistics & Data Science",
    "Theater",
    "Writing and Literature",
    "Zoology"
];

export const MINORS: string[] = [
    "American Indian and Indigenous Studies",
    "Anthropology",
    "Applied Psychology",
    "Architecture & Urban History",
    "Art",
    "Asian American Studies",
    "Astronomy and Planetary Science",
    "Black Studies",
    "Chemistry",
    "Chicana and Chicano Studies",
    "Chinese",
    "Classics",
    "Comparative Literature",
    "Earth Science",
    "Educational Studies",
    "English",
    "Feminist Studies",
    "French",
    "Game Studies",
    "German Studies",
    "History",
    "History of Art & Architecture",
    "Iranian Studies",
    "Italian",
    "Japanese",
    "Jewish Studies",
    "Labor Studies",
    "Language & Speech Technologies",
    "Latin American & Iberian Studies",
    "Lesbian, Gay, Bisexual, Transgender, & Queer Studies",
    "Linguistics",
    "Mathematics",
    "Mathematics for High School Teaching",
    "Media Arts and Design",
    "Medieval Studies",
    "Museum Studies",
    "Music",
    "Philosophy",
    "Physics",
    "Portuguese",
    "Poverty, Inequality, and Social Justice",
    "Professional Writing",
    "Religious Studies",
    "Russian",
    "Science and Mathematics Education",
    "Sociocultural Linguistics",
    "Spanish",
    "Spatial Studies",
    "Speech-Language Sciences & Disorders",
    "Statistical Science",
    "Teaching English to Speakers of Other Languages (TESOL)",
    "Theater",
    "Theater Production and Design",
    "Translation Studies"
  ];